version: "2"
services:
  node:
    image: goodjoblife/goodjobshare:stage
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - API_HOST=https://api-stage-v4.goodjob.life
        - CONTENTFUL_API_HOST=https://content-stage.goodjob.life
        - FACEBOOK_APP_ID=1844389232511081
    ports:
      - 39000:3001
